ministryofjustice/hmpps-manage-users

helm_deploy/manage-hmpps-auth-accounts/templates/deployment.yaml
helm_deploy/manage-hmpps-auth-accounts/templates/ingress.yaml

Reverts ministryofjustice/manage-hmpps-auth-accounts#3

Revert "DT-917: Switch out deprecated APIs"

---

helm_deploy/manage-hmpps-auth-accounts/templates/deployment.yaml
helm_deploy/manage-hmpps-auth-accounts/templates/ingress.yaml

Revert "Revert "DT-917: Switch out deprecated APIs (#3)" (#4)"

---

backend/controllers/authUserMaintenance.js
integration-tests/pages/menuPage.js
manage-accounts-specs/src/test/groovy/uk/gov/justice/digital/hmpps/manageusers/pages/AddRolePage.groovy
manage-accounts-specs/src/test/groovy/uk/gov/justice/digital/hmpps/manageusers/pages/AdminUtilitiesPage.groovy
manage-accounts-specs/src/test/groovy/uk/gov/justice/digital/hmpps/manageusers/pages/AuthUserCreatePage.groovy
manage-accounts-specs/src/test/groovy/uk/gov/justice/digital/hmpps/manageusers/pages/StaffRoleProfilePage.groovy
manage-accounts-specs/src/test/groovy/uk/gov/justice/digital/hmpps/manageusers/pages/UserSearchPage.groovy
manage-accounts-specs/src/test/groovy/uk/gov/justice/digital/hmpps/manageusers/pages/UserSearchResultsPage.groovy
manage-accounts-specs/src/test/groovy/uk/gov/justice/digital/hmpps/manageusers/specs/AdminUtilitiesSpecification.groovy
src/Admin/MaintainAuthUsers/containers/AuthUserCreateContainer.js
src/Admin/MaintainRoles/components/AddRole.js
src/Admin/MaintainRoles/components/AddRole.test.js
src/Admin/MaintainRoles/components/StaffRoleProfile.js
src/Admin/MaintainRoles/components/StaffRoleProfile.test.js
src/Admin/MaintainRoles/components/UserSearch.js
src/Admin/MaintainRoles/containers/AddRoleContainer.js
src/Admin/MaintainRoles/containers/StaffRoleProfileContainer.js
src/Admin/MaintainRoles/containers/UserSearchContainer.js
src/Admin/MaintainRoles/containers/UserSearchResultsContainer.js
src/Admin/containers/AdminUtilitiesContainer.js
src/Admin/containers/AdminUtilitiesContainer.test.js
src/Admin/containers/__snapshots__/AdminUtilitiesContainer.test.js.snap
src/routes.js

This deals with the content changes to the UI as described on the epic DT-931 where it was possible to make them without implementing the functional changes (which will come in further stories).

DT-956 Update wording

---

views/addGroup.njk
views/addRole.njk
views/createUser.njk

DT-1408: added select a group text to dropdown on create user page

---

backend/controllers/getGroups.js
backend/controllers/getGroups.test.js
backend/routes/manageGroupsRouter.js
integration-tests/integration/groups.spec.js
integration-tests/pages/authUserSearchPage.js
integration-tests/pages/groupsPage.js
integration-tests/pages/menuPage.js
views/groups.njk

DT-1477: ✨ Filter groups page

---

views/createUser.njk
views/search.njk

DT-2405: 💄 Decrease input widths

---

backend/controllers/searchWithFilter.test.js
backend/routes/searchApiFactory.js
backend/routes/searchApiFactory.test.js
backend/routes/searchDpsUserRouter.js
backend/routes/searchWithFilterDpsUserRouter.js

Extracted shared router code so it can be more easily tested (with bonus that it is shared)

DT-2441 Improve router test be extracting shared factory

---

backend/api/prisonApi.js
backend/api/prisonApi.test.js
backend/controllers/searchWithFilter.js
backend/controllers/searchWithFilter.test.js
backend/nunjucksSetup.js
integration-tests/integration/dpsuser.manage.spec.js
integration-tests/integration/dpsuser.search-with-filter.spec.js
integration-tests/pages/dpsUserSearchWithFilterPage.js
integration-tests/support/dpsuser.helpers.js
package.json
sass/application.scss
sass/components/_multi-select-filter.scss
static/js/multiselectfilter.js
views/components/multiselectfilter/macro.njk
views/components/multiselectfilter/template.njk
views/searchWithFilter.njk

Use the filter multiple check pattern from https://www.gov.uk/search/news-and-communications.
This requires:
- New multi filter component modelled on GDS patterns
- Non transpile Javascript supporting module
- Passing through all values to backend API

DT-2441 Allow multiple role search

---

backend/api/prisonApi.js
sass/_moj-overrides.scss
static/js/moj-filter-button-toggle.js
views/partials/layout.njk
views/searchWithFilter.njk

Improve responsiveness by enabling MoJ filtering hiding. When the screen is too small the  filter adds a close button to itself 
This requires:
* Initialising MoJ components
* Add component so filter can add a show / hide button
* Move filter tag component to above results so it is always visible
Also improve user view by adding additional `View details` link

DT 2441 Multiple Role Search Accessibiity

---

backend/config.js
backend/middleware/featureSwitches.js
backend/middleware/featureSwitches.test.js
backend/nunjucksSetup.js
backend/nunjucksSetup.test.js
backend/routes.js
helm_deploy/manage-hmpps-auth-accounts/templates/_envs.tpl
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
integration-tests/integration/dpsuser.search-with-filter.spec.js
integration-tests/pages/menuPage.js
integration-tests/support/dpsuser.helpers.js
static/js/moj-filter-button-toggle.js
views/components/multiselectfilter/template.njk
views/menu.njk
views/searchWithFilter.njk

Added descriptions to menu:
And hints to filter page:

Dt 2441 Improved copy and added new search behind feature switch

---

backend/controllers/searchWithFilter.js
backend/controllers/searchWithFilter.test.js

source is base url please a page identify

DT-2873 point at new survey and pass in a source

---

Dockerfile

Reverts ministryofjustice/hmpps-manage-users#312

Revert "DT-3045: update dockerfile for node 16 (correct folder names)"

---

sass/_govuk-overrides.scss
views/menu.njk

Change Background of manage users page as per  DPS landing page

HAAR-47: Change Background of manage users page

---

backend/controllers/userDetails.js
backend/controllers/userDetails.test.js
backend/routes/manageDpsUserRouter.js
backend/routes/manageDpsUserRouter.test.js
views/searchWithFilter.njk
views/userDetails.njk

HAAR-441: Displaying difference in email whilst change unverified

---

backend/api/manageUsersApi.js
backend/api/manageUsersApi.test.js
backend/api/oauthApi.js
backend/api/oauthApi.test.js
backend/routes.js
backend/routes/manageAuthUserRouter.js
integration-tests/e2e/errorhandling.cy.js
integration-tests/e2e/externaluser.create.cy.js
integration-tests/e2e/externaluser.manage.cy.js
integration-tests/e2e/groups.cy.js
integration-tests/mockApis/auth.js
integration-tests/mockApis/manageusers.js
views/searchDpsUsers.njk

HAAR-986:Amended Users Group endpoint from Auth to Manage Users endpoint

HAAR-986: Amended Users Group endpoint

---

README.md
backend/api/tokenVerificationApi.js
backend/api/tokenVerificationApi.test.js
backend/apis.js
backend/authentication/auth.ts
backend/config.ts
backend/data/manageUsersApi.ts
backend/index.js
backend/middleware/currentUser.js
backend/middleware/setUpAuth.js
backend/services/healthCheck.js
backend/sessionManagementRoutes.js
backend/setupHealthChecks.js
backend/utils/nunjucksSetup.js
cypress.env
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
integration-tests/e2e/health.cy.js
integration-tests/mockApis/tokenverification.js
integration-tests/plugins/index.js

Starting rename of a few things to match the template...trying to do a little and often

HAAR-878 Rename config fields to match template

---

backend/api/manageUsersApi.js
backend/api/oauthApi.js
backend/routes/searchExternalUserRouter.js
cypress.config.ts
integration-tests/e2e/externaluser.search.cy.js
integration-tests/mockApis/auth.js
integration-tests/mockApis/manageusers.js
integration-tests/support/externaluser.helpers.js

HAAR-868: Get list of searchable roles

---

backend/controllers/addEmailDomain.js
backend/controllers/addEmailDomain.test.js
backend/controllers/deleteEmailDomain.js
backend/controllers/deleteEmailDomain.test.js
backend/routes/createEmailDomainRouter.js
backend/routes/deleteEmailDomainRouter.js
integration-tests/e2e/emaildomain.delete.cy.js
integration-tests/mockApis/manageusers.js
integration-tests/pages/emailDomainDeletionPage.js
integration-tests/pages/emailDomainListingPage.js

Good morning All, please could somebody help out with this delete email domain tests PR.

HAAR-1221: delete email domain test and other update

---

backend/api/oauthApi.js
backend/api/oauthApi.test.js
integration-tests/mockApis/auth.js
integration-tests/support/dpsuser.helpers.js

I can't see where this is used

HAAR-1313 Remove unused /api/user/email stubs

---

backend/controllers/createExternalUser.js
backend/controllers/createExternalUser.test.js

Fixed 'Search Result' link after creation of  external user

HAAR-1350-ext-user-search-result

---

helm_deploy/hmpps-manage-users/values.yaml

Exclude Modsec rule (942440) REQUEST_COOKIES:hmpps-session-prod

HAAR-1748: Exclude Modsec rule (942440)

---

helm_deploy/hmpps-manage-users/values.yaml

Reverts ministryofjustice/hmpps-manage-users#594

Revert "HAAR-2943: disable MODSEC rule 913101 for user-agent request headers"

---

backend/config.ts
backend/middleware/currentUser.js
backend/middleware/currentUser.test.js
cypress.config.ts
helm_deploy/hmpps-manage-users/values.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-stage.yaml
integration-tests/e2e/menu.cy.js
integration-tests/pages/menuPage.js
views/menu.njk

This is hidden behind the role MANAGE_USER_ALLOW_LIST, which currently doesn't exist so can be merged to main

HAAR-3645: add tile for manage user allow list

---

backend/routes/userAllowList/addUser.ts
backend/services/userAllowListService.ts
helm_deploy/values-dev.yaml
helm_deploy/values-prod.yaml
integration-tests/e2e/userAllowlist/addUser.cy.ts
integration-tests/mockApis/manageUsersAllowList.ts

Also disable the user allow list tiles in dev and prod

HAAR-3645: show error if username already exists when adding
